load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "fakeacp_lib",
    srcs = ["main.go"],
    importpath = "github.com/gastownhall/gascity/internal/runtime/acp/testdata/fakeacp",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "fakeacp",
    embed = [":fakeacp_lib"],
    visibility = ["//:__subpackages__"],
)
